baseURL: "https://dadada.li/"
title: "dadada"
defaultContentLanguage: "en"
paginate: 5
theme: "smol"
enableRobotsTXT: true

params:
  author: "dadada"
  rss:
    includeContent: true

taxonomies:
  tag: "tags"

author:
  name: "dadada"


menu:
  main:
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 0
  - identifier: talks
    name: Talks
    title: Talks
    url: /talks/
    weight: 0
